// autogenerated

float fontMeasurements[59] = {
    0.972602,  // gjFont01
    0.930131,  // gjFont02
    0.977064,  // gjFont03
    1.054455,  // gjFont04
    1.03398,   // gjFont05
    0.918103,  // gjFont06
    0.93421,   // gjFont07
    1.03398,   // gjFont08
    0.942477,  // gjFont09
    0.822393,  // gjFont10
    0.930131,  // gjFont11
    1.039024,  // gjFont12
    1.196629,  // gjFont13
    1.054455,  // gjFont14
    0.855421,  // gjFont15
    0.918103,  // gjFont16
    0.959459,  // gjFont17
    1.065,     // gjFont18
    0.93421,   // gjFont19
    0.803773,  // gjFont20
    0.986111,  // gjFont21
    1.014285,  // gjFont22
    0.87295,   // gjFont23
    0.777372,  // gjFont24
    0.922077,  // gjFont25
    0.995327,  // gjFont26
    1.121052,  // gjFont27
    0.986111,  // gjFont28
    0.898734,  // gjFont29
    1.03398,   // gjFont30
    0.926086,  // gjFont31
    0.950892,  // gjFont32
    1.103626,  // gjFont33
    0.977064,  // gjFont34
    1.092307,  // gjFont35
    0.950892,  // gjFont36
    0.930131,  // gjFont37
    1.039024,  // gjFont38
    0.977064,  // gjFont39
    0.876543,  // gjFont40
    1.014285,  // gjFont41
    0.990697,  // gjFont42
    1.044117,  // gjFont43
    0.995327,  // gjFont44
    0.981566,  // gjFont45
    0.906382,  // gjFont46
    1.044117,  // gjFont47
    1.065,     // gjFont48
    0.891213,  // gjFont49
    1.019138,  // gjFont50
    1.145161,  // gjFont51
    1.044117,  // gjFont52
    1.059701,  // gjFont53
    0.942477,  // gjFont54
    1.121052,  // gjFont55
    1.145161,  // gjFont56
    0.977064,  // gjFont57
    1.189944,  // gjFont58
    1.139037,  // gjFont59
};

float chatFontRatio = 0.389671;